# Generated by Django 2.2.12 on 2020-06-03 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('code_of_verification', models.CharField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filtercode', models.CharField(max_length=30, unique=True)),
                ('filtername', models.CharField(max_length=30)),
                ('filterdetail', models.CharField(max_length=300)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MainPack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packagecode', models.CharField(max_length=30, unique=True)),
                ('isbytime', models.BooleanField(default=True)),
                ('isbyusage', models.BooleanField(default=False)),
                ('price', models.FloatField()),
                ('exfiltermonth', models.IntegerField(default=6)),
                ('exfiltervolume', models.IntegerField(default=2500)),
                ('packagedetail', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffcode', models.CharField(max_length=30, unique=True)),
                ('staffshort', models.CharField(default='', max_length=5)),
                ('staffname', models.CharField(max_length=30)),
                ('staffcontact', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactname', models.CharField(max_length=100)),
                ('billingaddress1', models.TextField(max_length=100)),
                ('installaddress1', models.TextField(max_length=100)),
                ('billingaddress2', models.TextField(blank=True, max_length=100, null=True)),
                ('installaddress2', models.TextField(blank=True, max_length=100, null=True)),
                ('contactno', models.CharField(max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('invitationcode', models.CharField(max_length=20, unique=True)),
                ('joindate', models.DateField(auto_now_add=True, null=True)),
                ('source', models.CharField(choices=[('Online', 'Online'), ('Referral', ' Referral'), ('Old', 'Old Customer'), ('Phone ', ' Phone Call')], max_length=20)),
                ('comment', models.TextField(blank=True, max_length=300, null=True)),
                ('isconfirm', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machineid', models.CharField(max_length=100, unique=True)),
                ('installaddress1', models.TextField(max_length=100)),
                ('installaddress2', models.TextField(blank=True, max_length=300)),
                ('photoncode', models.CharField(max_length=100)),
                ('mac', models.CharField(blank=True, max_length=100)),
                ('installdate', models.DateField(auto_now_add=True, null=True)),
                ('nextservicedate', models.DateField(blank=True, null=True)),
                ('producttype', models.CharField(choices=[('WPU', 'Water Purifier'), ('U', 'Under Sink'), ('F', 'Filter')], max_length=3)),
                ('price', models.FloatField()),
                ('main_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OneToOne.MainPack')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casetype', models.CharField(choices=[('Filter replacement', 'Filter replacement'), ('Urgent Repair', 'Urgent Repair'), ('Installation', 'Installation'), ('Checking', 'Checking')], max_length=100)),
                ('scheduledate', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('action', models.TextField(blank=True, max_length=100)),
                ('suggest', models.TextField(blank=True, max_length=100)),
                ('comment', models.TextField(blank=True, max_length=100)),
                ('iscompleted', models.BooleanField(blank=True, default=False)),
                ('filters', models.ManyToManyField(blank=True, to='OneToOne.Filter')),
                ('handledby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OneToOne.Technician')),
                ('machines', models.ManyToManyField(to='OneToOne.Machine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
